sudo: required

language: node_js
node_js:
  - "8"
  - "14"

env:
  - TEST_PLUGINS='default'
  - TEST_PLUGINS='meteor'
  - TEST_PLUGINS='mongo,docker,proxy'
  - TEST_OPTIONS="--non-root"
  - TEST_OPTIONS=""

services:
  - docker

before_script:
  - echo 'DOCKER_OPTS="--storage-driver=devicemapper"' | sudo tee --append /etc/default/docker >/dev/null && sudo service docker restart

script: npm run test -- --plugins="$TEST_PLUGIN" $TEST_PLUGINS
